using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SriReportSuite.Models
{
    public class Flow
    {
        [Key]
        public int FlowID { get; private set; }
        [Required, ForeignKey("Study")]
        public int StudyID { get; set; }
        public string Structure { get; set; }
        public float ForwardFlow { get; set; }
        public float ReverseFlow { get; set; }
        public int HeartRate { get; set; }
    }

    public class Image
    {
        [Key]
        public int ImageID { get; private set; }
        [Required, ForeignKey("Study")]
        public int StudyID { get; set; }
        public byte[] Img { get; set; } //byte array to hold the image
        public string ImgDesc { get; set; } //80 character limit
    }

    public class Volume
    {
        [Key]
        public int VolumeID { get; private set;  }
        [Required, ForeignKey("Study")]
        public int StudyID { get; set; }
        public string Chamber { get; set; }
        public float EDV { get; set; } //end-diastolic volume
        public float ESV { get; set; } //end systolic volume
        public int HeartRate { get; set; }
    }

    public class Measurement
    {
        [Key]
        public int MeasurementID { get; set; }
        [Required, ForeignKey("Study")]
        public int StudyID { get; set; }
        public string Strucuture { get; set; }
        public string Measure { get; set; }
        public string MeasureSequence { get; set;  } //sequence measurement taken
    }

    public enum StudyStatus
    {
        Unknown, Waitlisted, Scheduled, Performed, PreliminaryReport, FinalReport, AmendedReport
    }

    public enum StudyType
    {
        PaedCardiacMRI,  ACHDCardiacMRI, MRICath_PVR_Study,   MRI_Stress_Perfusion,  FetalCardiacMRI , FeedWrapMRI
    }
    public enum Echocardiogram
    {
        None, Transthoracic, Transesophageal, Both_TTE_TOE
    }
    public class Study
    {
        [Key, ConcurrencyCheck]
        public int StudyID { get; set; }

        [Required, ForeignKey("Patient")]     //Foreign key to patient table
        public int PatientID { get; set; }
        [Required, ForeignKey("RefConsultant")] //Note convention on naming <principal entity name><primary key property name>
        public int ConsultantID { get; set; } //ID of consultant referring patient - foreign key to class Consultant
        [Required, ForeignKey("Clinic")] //Clinic where patient referred from
        public int ClinicID { get; set; }

        public DateTime StudyDate { get; set; }
        public DateTime ReportDate { get; set; }
        [Timestamp]
        public byte[] LastUpdated { get; set;  } //Last time study data was changed - Autogenerated database value
        public string StudyComment { get; set; }

        public StudyStatus StudyStatus { get; set; } //could be "Unknown", "Waitlisted", "Scheduled", "Performed", "Preliminary Report", "Final Report", "Amended Report" - only
        public StudyType StudyType { get; set; }
        public bool GA { get; set; } //General Anaesthesia - Yes or No
        public string Echo { get; set; } //stores if echo done and if so - TOE / Transthoracic - hence "None", "Transthoracic", "Transesophageal", "Both TTE and TOE"
        public bool Bronchoscopy { get; set; } //Yes or No
        public Echocardiogram Echocardiogram { get; set; } //types - None, Transthoracic, Transesophageal only
        public decimal Weight { get; set; }
        public decimal Height { get; set; }
        public decimal CVP { get; set; }
        public int Saturations { get; set; }
        public decimal FiO2 { get; set; } //as percentage, default 21%
        public string Indication { get; set; } //256 words describing indication
        public string Contrast { get; set; } //limit to None, Dotarem or Gadovist
        public string ContrastDose { get; set; } //if not None, then 0.2* Weight as default
        public string ScanSummary { get; set; } //comma seperated list of sequences used
        public string Findings { get; set; } //up to 5000 word text of findings (html) - should store text formatting and links to pictures.
        public string Summary { get; set; } //up to 1000 word summary of findings (html) - storing text formatting and links to pictures

        [ForeignKey("Registar")]
        public int RegID { get; set; } //ID of registar doing report - foreign key to Registrar.cs
        [Required, ForeignKey("MRIConsultant")] //See naming convention of variable follows <navigation property name>_<primary key property name>
        public int MRIConsultantConsultantID { get; set; } //ID of consultant supervising study - foreign key to class MRIConsultant (superclass of Consultant)

        public virtual ICollection<Flow> Flows { get; set; } //virtual: means this method is over-ridden in inherited class (it is only a place holder)

        public virtual ICollection<Volume> Volumes { get; set; }

        public virtual ICollection<Image> Images { get; set; }

        public virtual ICollection<Measurement> Measurements { get; set; }

    }
}
//Nice reference about using List<T> vs. ICollection<T> at: http://stackoverflow.com/questions/7655845/icollectiont-vs-listt-in-entity-framework. In summary:
/* 
Entity Framework would use ICollection<T> because it needs to support Add operations, which are not part of the IEnumerable<T> interface. 
Also note that you were using ICollection<T>, you were merely exposing it as the List<T> implementation.List<T> brings along with it IList<T>, ICollection<T>, and IEnumerable<T>.
As for your change, exposing via the interface is a good choice, despite List<T> working.The interface defines the contract but not the implementation.
The implementation could change. In some instances, perhaps the implementation could be a HashSet<T>, for example. 
(This is a mindset you could use for more than just Entity Framework, by the way. A good object-oriented practice is to program towards the interface and not the implementation.
Implementations can and will change.)
*/

 /* ICollection declared as virtual to take advantage of lazy loading and also to code implementation seperately */